- theories/ZArith/BinInt.v
They can slow down printing badly, cf coq/coq#9083
> Deprecate and make parsing only eq_sym wrappers in BinInt

- CONTRIBUTING.md
The contributors team does not exist here, and the label categories do not either.
We can either remove this section or create such a team and labels, but it looks like overengineering to me to create these before they are really needed.
> Remove section from the contributing guide that does not apply to this repo.

- doc/changelog/01-added/75-add-length_app_comm.rst
- theories/Lists/List.v
This PR adds to List.v a lemma: `Lemma length_app_comm : forall l l' : list A, length (l++l') = length (l'++l).`
I'd like to preface by saying that I am new to Coq so may be ignorant of many things. However, I was in need of such a lemma in one of my proofs and was surprised that an obvious fact such as this did not already exist in the stdlib. I hope that `length_app_comm` is a good name for this. I read over https://github.com/coq/coq/pull/18564 where the naming convention of these lemmas was discussed, and I believe that I followed it correctly.
One thing I am unsure about is if I was correct to add the new lemma under the `Global Hint Rewrite` here:
```coq
Global Hint Rewrite
rev_involutive (* rev (rev l) = l *)
rev_unit (* rev (l ++ a :: nil) = a :: rev l *)
map_nth (* nth n (map f …
```
> add lemma length_app_comm

- test-suite/bugs/bug_16803.v
Currently the universes associated with a record get names for both the record and its projections (with all these names pointing at the same raw universe).
coq/coq#20095 will only declare the name for the record itself.
> Use forward compatible univ names in test for #16803

- doc/sphinx/conf.py
Send back to the Coq refman for older versions.
This is a proposal to fix #76 (not the one I suggested in the issue).
I couldn't test it because the version switcher doesn't seem to work locally for me (with or without this patch).
> Update version switcher for stdlib.

- doc/changelog/01-added/89-Zfloor.rst
- theories/Reals/Reals.v
- theories/Reals/Zfloor.v
Reopening of #89 that was unfortunately merged while it was broken but CI failed to show it.
> Adding Zfloor and Zceil to Reals

- doc/common/styles/html/coqremote/footer.html
- doc/common/styles/html/coqremote/header.html
This allows to integrate the generated HTML smoothly into the new rocq-prover.org website.
Fixes coq/coq#19976
> Header and footer for new website (rocq-prover.org) integration

- .gitignore
- doc/common/macros.tex
- doc/sphinx/_static/coqdoc.css
- doc/sphinx/introduction.rst
- doc/sphinx/language/coq-library.rst
- doc/stdlib/Library.tex
This updates (actually, sets as it was not there) the Stdlib refman coqdoc.css style file to the new Rocq Prover defaults.
> Stdlib rocq manual

- doc/stdlib/dune
Fixes / closes #128 
I think it is sound to do it like this, as long as the published documentation respects the folder layout: 
version/stdlib
version/corelib
> Use a relative link for the Corelib library references, fixing #128

- test-suite/Makefile
ARCH is from coq_config_to_make which we don't have in this repo
> test suite fix OS detection

- doc/changelog/02-added/134-n-iter-op.rst
- doc/changelog/11-standard-library/19751-n-iter-op.rst
- theories/NArith/BinNat.v
- theories/NArith/BinNatDef.v
Repeat of https://github.com/rocq-prover/rocq/pull/19751 which was closed without a review after 83 days. I still think this is a useful feature and should be landed.
> add N.iter_op and supporting lemmas

- doc/changelog/02-added/135-zmodoffset.rst
- doc/stdlib/index-list.html.template
- theories/All/All.v
- theories/Make.zarith
- theories/ZArith/ZArith.v
- theories/ZArith/ZModOffset.v
Repeat of https://github.com/coq/coq/pull/19753 which had a green CI but no discussion.
> Added ZModOffset including Z.omodulo and Z.smodulo

- theories/ZArith/Zbool.v
> correct typos in deprecated warnings in Zbool.v

- Makefile
Also make `dune`, `all`, `install` and `dune-install` .PHONY
> Add clean in Makefile

- .github/workflows/alpine.yml
This shaves 2 minutes (~40%) off the time until first useful CI feedback ([experiment](https://github.com/andres-erbsen/stdlib/actions/runs/15426576433?pr=1), [control](https://github.com/andres-erbsen/stdlib/actions/runs/15426576177?pr=1)).
> CI-test dune build on Alpine Linux

- test-suite/output/NsatzGuessOnce.out
- test-suite/output/NsatzGuessOnce.v
- theories/nsatz/NsatzTactic.v
- theories/setoid_ring/Cring.v
- theories/setoid_ring/Ncring_tac.v
This is essentially a follow-up to https://github.com/rocq-prover/rocq/pull/18325; it's also a way towards https://github.com/rocq-prover/stdlib/pull/155 without https://github.com/rocq-prover/rocq/issues/20695. Fiat-crypto nsatz already includes this change, and this PR is one more step towards reconciling the two.
> nsatz: resolve domain early and thread the instance

- .nix/config.nix
- .nix/rocq-overlays/stdlib-subcomponents/default.nix
- doc/changelog/01-changed/154-split-FinFun.rst
- doc/stdlib/depends.dot
- doc/stdlib/index-list.html.template
- theories/All/All.v
- theories/Lists/Finite.v
- theories/Make.lists
- theories/Make.sorting
- theories/Sorting/Permutation.v
- theories/Vectors/FinFun.v
- theories/Zmod/Bits.v
- theories/Zmod/ZmodInv.v
- theories/Zmod/ZstarBase.v
- theories/Zmod/ZstarDef.v
- theories/micromega/RingMicromega.v
- https://github.com/mit-plv/fiat-crypto/pull/2091
- https://github.com/rocq-community/corn/pull/215
- https://github.com/adampetcher/fcf/pull/49
- https://gitlab.mpi-sws.org/iris/stdpp/-/merge_requests/617
> split FinFun and Permutation into List and Vector

- doc/changelog/02-added/156-zmod-nsatz.rst
- doc/stdlib/index-list.html.template
- test-suite/success/Nsatz.v
- theories/All/All.v
- theories/Make.zmod
- theories/Reals/RNsatz.v
- theories/ZArith/Zdivisibility.v
- theories/Zmod/Zmod.v
- theories/Zmod/ZmodDef.v
- theories/Zmod/ZmodNsatz.v
- theories/setoid_ring/Ncring_tac.v
In https://github.com/rocq-prover/rocq/pull/18325 , Ltac-driven reification was sufficient because the extension point was used only once. Here we have two users (R and Zmod), so I introduced a hint-extern typeclass just for the extension case.
> Zmod nsatz

- theories/extraction/ExtrOcamlZBigInt.v
@Lysxia could you have a look?  I believe this was probably just a typo in https://github.com/rocq-prover/stdlib/commit/ed79c16c93ad1cc1c9138dd1a95c31aa31b6575b
> Fix extraction of N.eqb and N.eq_dec in ExtrOcamlZBigInt

- theories/dune
This fixes a bug for composed builds, introduce in #167.
As the rule stands, dune will try to generate the All.v file before both `rocq` and `Corelib.Init.Prelude.vo` have been built, which are both needed for the script.
Unfortunately, given the way rocq and prelude work, we need to depend on the full `rocq-core` package, so things are in the expected places before the generation of `All.v`.
This would linearize the stdlib build: we cannot run `coqdep` now for the
`Stdlib` until the whole `rocq-core` package is built.
We mitigate this by excluding `All.v` from the list of modules in the
`Stdlib` coq.theory file.
> [build] Fix missing deps in dune rule for All.v file

- theories/Numbers/Natural/Abstract/NSub.v
These lemmas mirror the lemmas by the same name on integers.
Here is the argument: Z.add_simpl_l exists, users would expect Nat.add_simpl_l to exist (a corresponding lemma
used to exist, named minus_plus, but it cannot be replaced by a single theorem).
> adds Nat.add_simpl_l and Nat.add_add_simpl_l_l 

- test-suite/output/NotationsCoercionsString.v
- test-suite/output/StringSyntax.v
- test-suite/output/simpl.v
- theories/_CoqProject
- theories/dune
Adapt to https://github.com/rocq-prover/rocq/pull/20855
We should really sort out that warning situation. But let only handle the overlay for now.
> Adapt to https://github.com/rocq-prover/rocq/pull/20855
